### ISSUE TITLE
SetupConfigurator removes all other configurations that is not included configOptions

### ISSUE THREAD

**Issue by JoshRosenstein** [pete-thompson/spotfire-visuals#16]
For example, currently cannot use for visualizations that depend on other non user-configurable options ie spotfire document properties, as the configurator currently clears it out upon updating. 
https://github.com/pete-thompson/spotfire-visuals/blob/8b7bb0bc970054c7de18cfa9c65e0074a529a5c2/lib/JSVizConfigurator.js#L70

Quick work around was to add the document property to the visualizations default config IE:
```js
SetupViz({
  defaultConfig: {
    myDocProp: '%%DocProp.myDocProp%%',
    xAxisColumn: 'ColA'
  },
  configOptions: [
    {
      caption: 'Column to use to X Axis',
      type: 'column',
      name: 'xAxisColumn',
      tab: 'Axes'
    }]
...
```
and by doing a shallow merge prior to calling setConfig :
```js
window.setConfig(JSON.stringify({ ...defaultConfig, ...answer}))
```
Not optimal but works, maybe adding a new config type (document-property) in order to set the document property name and handle its formatting prior to calling setConfig.

**Comment by pete-thompson** [comment]
Thanks Josh. I'll have a look at adding a config type along the lines of 'not-editable' or 'ignore' meaning that it's recognised but not modified by the configurator.

You could also allow the configuration item to be edited using a text box as a workaround - not ideal if you want it to be hidden from users completely, but at least the configurator wouldn't remove it.

**Comment by pete-thompson** [comment]
I've made a simpler change - I only update parts of the configuration that are defined in the list of user-configurable options. Anything entered in the JSViz properties form for non-editable properties should be left untouched.
