### ISSUE TITLE
Support Dot Notation Configs

### ISSUE THREAD

**Issue by JoshRosenstein** [pete-thompson/spotfire-visuals#17]
Currently, any meta-characters in the option name breaks JSVizConfigurator due to invalid selector ids. One use case would to allow dots since it is common to represent nested objects in a flattened dot notation format.

For example while utilizing a graphing library such as plotly, and configuring user controls for individual traces, user configs may grow to be quite complex and may require name spacing to handle splitting out the configurations.
IE:
![image](https://user-images.githubusercontent.com/32781407/94056996-a1d86a00-fda4-11ea-8a8f-004a62b84862.png)

A workaround i did was to wrap all selectors like so:
```js
function safeSelector (str) {
  return str.replace(/\./g, '_')
}
```

https://github.com/pete-thompson/spotfire-visuals/blob/8b7bb0bc970054c7de18cfa9c65e0074a529a5c2/lib/JSVizConfigurator.js#L179
```js
var fieldId = safeSelector('QIConfigField-' + option.name)

```

**Comment by pete-thompson** [comment]
I've changed the logic so that it creates unique IDs without using the name - so the latest version should work for you
