### ISSUE TITLE
Triggering JSViz JSON update after Data Function

### ISSUE THREAD

**Issue by rsakai** [pete-thompson/spotfire-visuals#40]
This isn't an issue with JSViz examples, but I have an issue that JSViz does not update when the underlying data is updated via a Data Function.  I am using a Python script that takes a document property into account to generate and replace an existing table.  When I point this table in JSViz component, and when I trigger the data function to update the table, it does not update the JSViz even though the data table content is updated.  Have you come across this issue?  Do you know any work around? Or, am I missing something???

**Comment by pete-thompson** [comment]
It should call the render function again with the new data. If it’s Not using my JSViz components then your best To raise it on TIBCO’s community as they own JSViz itself.
