### ISSUE TITLE
Radar Chart axis range issue

### ISSUE THREAD

**Issue by jplerxt** [pete-thompson/spotfire-visuals#6]
Hi Pete,

It does not seem like the axis range has any effect when it auto-scales (i.e., set "0" for min and max), under single row markings. I think this is a feature.

If I do not use a single scale for all axes, and auto-range them, then for any single-row marking, I get a tight circle at the minimum for my selection. If I mark more than one row, then I will get more range in the chart. Does the auto-ranging only apply to the marked data set then, and not all rows in the data table? I guess so - is there a way to transfer the range of each column to the radar chart instead? It looks like only one range is supported.

thanks,
JP Lee
NIBR

**Comment by pete-thompson** [comment]
Thanks JP!

The auto scale is based on the data that you send to the visual, so yes - a single row of data with auto scale is going to draw a rather useless tight circle.

One possible way to work around it would be to always send a row with minimum values and a row with maximum values - pretty ugly, but would force the automatic range.

I've a couple of ideas for enhancements to support scales based on the full dataset:

- When data is provided in rows, I could add support for columns that hold the min/max values for each axis. You'd then need to update the data configuration to send the min/max values
- I could update the axis minimum and maximum properties to support multiple values, thus allowing for fixed axes with different ranges.
- I could allow for a second table of data to be configured in the data properties which sent the full dataset without markings, then base the auto ranges off that.

Not sure when I'll have chance to play with ideas, but at least I know about the issue :)

**Comment by jplerxt** [comment]
Thanks Pete.  I am completely new to JSViz, and don't have that firm of an understanding of it yet, but is it also possible for the viz to call back to the Spotfire core API to say run a python script that would supply the min-max values for the columns that are configured for the chart? So, with each added column, the viz could call back and get the min-max. I guess if you filter the table, then the min-max vals would change, so there'd need to be some flexibility built in. I guess that supplying the data in columns or tables as you ponder would negate the need for coding.

It looks like there needs to be more selectivity in setting up the axis ranges. Meanwhile, we will look into creating fixed ranking columns for the columns that we send to the radar chart. I don't think that sending the full data set is a good idea, if that's what you mean above in point 3. 

JP

**Comment by pete-thompson** [comment]
Thanks JP - using document properties and Iron Python would be possible, but painful.

How large is your dataset? If it's large, another possibility would be to send 3 tables (!), the first being your filtered data, the second being a table with one row calculating the min values, the third being one row with the max values. JSViz would allow easy enough configuration of the extra tables - I would just need to write some better instructions on how to do it!

**Comment by GerardConway** [comment]
Hi jplerxt,

Probably the easiest work around right now is to Normalize your data.  You can do this by adding a Normalization transformation to your data, where you scale each of your numeric input columns between 0 and 1 (other methods are also available) and produce new scaled output columns.  Then use these normalized columns as input to the radar plot.  This will then give you the radar plot you are looking for.

Hope that helps,
Gerard


![normalized radar](https://user-images.githubusercontent.com/67281047/86109790-aa2e4b00-babc-11ea-9e55-6190c28d960e.png)

**Comment by GerardConway** [comment]
Normalization Transformation in the Data Canvas

![normalization transformation](https://user-images.githubusercontent.com/67281047/86110082-05f8d400-babd-11ea-8e8e-b55f99cb2d1a.png)

**Comment by pete-thompson** [comment]
Looks like I forgot to add a comment when I closed this! The latest version of the visualisation has the ability to process any 'additional tables' configured in JSViz and include them in the axis sizing without plotting them. This means it's now possible to send extra data giving the min/max ranges for the axes. I've updated the example on Tibco's wiki to show this in action.
