### ISSUE TITLE
Numeric value shown in the centre of the gauge is always '0'

### ISSUE THREAD

**Issue by GerardConway** [pete-thompson/spotfire-visuals#7]
The numeric value shown in the centre of the gauge is always '0'.  It's the same situation in the screenshot on the community page.  I was expecting it to be the numeric 'value' passed in and the same as that graphically displayed in the gauge.  I'm currently testing on v7.11.

**Comment by pete-thompson** [comment]
Thanks Gerard. Looks like this hasn't worked for a long time (we have folks here using these libraries so presumably they haven't noticed the value being 0!). I'm using a library to draw the gauges and it appears the version I have is ancient - I'm updating my code to use the latest version of the library and will publish a fixed version shortly...

**Comment by pete-thompson** [comment]
I've fixed this - hopefully you'll automatically pick up the new released version.

**Comment by GerardConway** [comment]
Thanks Pete
